{
	
	'name' : 'Kamil Accounting - Install All',
	'Author' : 'Alargm Ahmed - Nada Hassan',
	'application' : True,
	'sequence' : 0,
	'depends' : ['base',
		'account',
		'account_accountant',
		'account_asset',
		'account_reports',
		'account_reports_followup',
		'html_text',
		'kamil_accounting_base',
		'kamil_accounting_revenues_collection',
		'kamil_accounting_money_supply',
		'kamil_accounting_assets',
		'kamil_accounting_bank_cash_balance_sheet',
		'kamil_accounting_budget',
		'kamil_accounting_claims',
		'kamil_accounting_financial_ratification',
		'kamil_accounting_customization',
		'kamil_accounting_reports',
		'web_notify',
		'web_rtl',
		],
}
