# -*- coding:utf-8 -*-
from . import recipients_performance_wiz
from . import wiz_ratification_report
from . import wiz_ratification_list
from . import account_statement_wizard
from . import wiz_revenues_budget
from . import wiz_compare_revenues
from . import wiz_compare_revenues_companies
from . import payment_report
from . import wiz_revenues_specified_period
from . import wiz_budget_monthly
from . import wiz_bank_statement
from . import wiz_revenues_journal
from . import wiz_revenues_analysis_subgroups
from . import wiz_detailed_revenue_synthesis
from . import wiz_account_move
from . import wiz_expenses_specified_period
from . import wiz_compare_expenses
from . import wiz_compare_expenses_companies
from . import wiz_expenses_journal
from . import wiz_expenses_analysis_subgroups
from . import wiz_detailed_expenses_synthesis
from . import wiz_trial_balance
from . import wiz_profit_loss
from . import wiz_balance_sheet
from . import wiz_general_journal
from . import consolidated_account_statement_wizard
from . import wiz_clarifications